export const utlån = new Map<string, Record<string, unknown>>();

export const defaultFnr = "01067434656";

utlån.set(defaultFnr, {
  hjelpemidler: [
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "241303",
      isoKategori: "Fjernstyringssystemer",
      beskrivelse: "Radiomottaker BJ-232 1 rele",
      hmsnr: "254535",
      serieNr: null,
      datoUtsendelse: "2024-06-25 15:24:12",
      ordrenummer: "9185073",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "182103",
      isoKategori: "Åpnere og lukkere for dører",
      beskrivelse:
        "Automatikk slagdør tung Geze EMD-F komplett med returfjær dørbladvekt inntil 230 kg",
      hmsnr: "254370",
      serieNr: null,
      datoUtsendelse: "2024-06-25 15:24:12",
      ordrenummer: "9185073",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "182115",
      isoKategori: "Låser",
      beskrivelse: "Låskasse TV560 H 2-falle m/vaktmesterknapp",
      hmsnr: "166481",
      serieNr: null,
      datoUtsendelse: "2024-06-25 15:24:12",
      ordrenummer: "9185073",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "241303",
      isoKategori: "Fjernstyringssystemer",
      beskrivelse: "IR/radio sender BJ-261 Control 4 oppladbar",
      hmsnr: "254544",
      serieNr: null,
      datoUtsendelse: "2024-06-25 15:24:12",
      ordrenummer: "9185073",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090333",
      isoKategori: "Badetøy",
      beskrivelse: "Badebukse inko Helly Hansen neopren sydd etter mål",
      hmsnr: "042405",
      serieNr: null,
      datoUtsendelse: "2024-02-20 12:52:10",
      ordrenummer: "8931068",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Badebukse for inkontinente",
      grunndataBeskrivelse:
        "Badebuksen som blir produsert kun etter individuelle mål.\nBadebukse for inkontinente er laget i  vanntett materiale med neoprenlinninger i midje og lår.\n\n",
      grunndataKategori: "Badetøy",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/50768.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/042405",
      grunndataKategoriKortnavn: "Badetøy",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "091203",
      isoKategori: "Flyttbare toalettstoler med og uten hjul",
      beskrivelse:
        "Dusjtoaastol R82 Heron sb55 sd45 sh56-78 hjul arml fast oppfell benst delt avtak utfell tilt el pols",
      hmsnr: "297340",
      serieNr: null,
      datoUtsendelse: "2024-01-15 13:50:50",
      ordrenummer: "8920575",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Heron elektrisk",
      grunndataBeskrivelse:
        "Høyderegulerbar dusj- og toalettstol med elektrisk tilt, rygg, armlener, hodestøtte og benstøtte. Fire låsbare hjul. Leveres med polster til sete og rygg, brystbelte, hoftebelte og feste til bekken. Maks brukervekt 130 kg.",
      grunndataKategori: "Kombinerte dusj- og toalettstoler",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65662.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/297340",
      grunndataKategoriKortnavn: "Dusj-/toalettstol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181218",
      isoKategori: "Madrasser",
      beskrivelse:
        "Madrass Procell 834 b85 l200 h20 polyuretan brukervekt200 PU stretch dynamisk 20seksjoner",
      hmsnr: "286889",
      serieNr: null,
      datoUtsendelse: "2023-12-11 12:49:04",
      ordrenummer: "8889785",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "ProCell 834 85x200",
      grunndataBeskrivelse:
        "Dynamisk luftmadrass med tolags cellesystem for å kunne avlaste enkelte trykkpunkter totalt fra trykk. Cellene er utskiftbare. Madrassen kan stilles inn på kontinuerlig lavtrykk eller vekslende trykk. Leveres med avtagbart, elastisk inkontinenstrekk og pumpe. Finnes i bredder mellom 85-120 cm. Lengde: 200/210 cm. Maksimal brukervekt 200 kg. ",
      grunndataKategori: "Madrasser dynamiske",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/64920.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/286889",
      grunndataKategoriKortnavn: "Madrass",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "122306",
      isoKategori: "Elektriske rullestoler med motorisert styring",
      beskrivelse:
        "Ers styrel MC1144 Low Rider Spinalus-3 FWD sb45 sd35-55 rh55-60 seteløft el rygg vreg el tilt el benst el 10km/t",
      hmsnr: "302005",
      serieNr: "867140",
      datoUtsendelse: "2023-12-01 09:15:11",
      ordrenummer: "8671810",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "MC 1144 Low Rider Spinalus-3 FWD",
      grunndataBeskrivelse:
        "Elektrisk rullestol med forhjulsdrift for begrenset utendørs bruk. Rullestolen har lav setehøyde og påmontert rullestoldel for bilfeste (Dahl Docking). Elektrisk regulering av seteløft, tilt, rygg, benstøtte og legglengde. Leveres som standard med Spinalus-3 sitteenhet med hodestøtte. Setebredde: 40-55 cm. Maks brukervekt: 150 kg. ",
      grunndataKategori:
        "Elektriske rullestoler motorisert styring begrenset utebruk",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/66140.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/302005",
      grunndataKategoriKortnavn: "Elektrisk rullestol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse:
        "Pute sete ROHO Quadtro Select mid-profil b36,5 d38,5 hforan8,5 hbak8,5 luft trekk polyester",
      hmsnr: "299409",
      serieNr: null,
      datoUtsendelse: "2023-08-10 12:56:20",
      ordrenummer: "8671953",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "ROHO Quadtro Select mid-profil 36,5x38,5",
      grunndataBeskrivelse:
        "Trykkfordelende sittepute med luftceller delt inn i fire luftkammer. Luftmengden i hvert kammer kan tilpasses individuelt med pumpe. Minnekontroll styrer luftnivået i de fire uavhengige cellekamrene. Passer til rullestoler med plan- og hengekøyesete. Høyde: 8,5 cm. Leveres med to trekk. ",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65996.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/299409",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "122203",
      isoKategori: "Manuelle armdrevne rullestoler",
      beskrivelse: "Mrs bak komf azalea sb44-49 sd43-50 rh54-71 tilt",
      hmsnr: "279774",
      serieNr: "829993",
      datoUtsendelse: "2022-10-31 10:09:09",
      ordrenummer: "8090634",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "REA Azalea SB44 SD43-50",
      grunndataBeskrivelse:
        "Azalea er en komfortrullestol med manuell regulering av tilt og ryggvinkelen. Den har høyderegulerbare kjørehåndtak og leveres med sittepute (FloShape). Azalea tilfredsstiller kravene for bruk som sete i kjøretøy. Setehøyde: 40-45 cm. Maks brukervekt: 135 kg. Totalvekt i str. 39-44x43-50: 41,8 kg. ",
      grunndataKategori: "Manuelle rullestoler komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/64845.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/279774",
      grunndataKategoriKortnavn: "Manuell rullestol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse: "Pute sete StarLock 13 b46 d56 h13 luft polyester/spandex",
      hmsnr: "244993",
      serieNr: null,
      datoUtsendelse: "2022-10-31 10:05:05",
      ordrenummer: "8159819",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "StarLock 13 b46 d56",
      grunndataBeskrivelse:
        "Trykkfordelende sittepute med  luftceller. Luften kan låses mellom cellene. Luftmengden tilpasses individuelt med pumpe. Passer til rullestoler med plan- og hengekøyesete. Høyde: 13 cm. Leveres med to trekk. ",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65985.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/244993",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse: "Pute sete StarLock 13 b46 d51 h13 luft polyester/spandex",
      hmsnr: "244992",
      serieNr: null,
      datoUtsendelse: "2022-09-05 14:33:39",
      ordrenummer: "8159820",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "StarLock 13 b46 d51",
      grunndataBeskrivelse:
        "Trykkfordelende sittepute med  luftceller. Luften kan låses mellom cellene. Luftmengden tilpasses individuelt med pumpe. Passer til rullestoler med plan- og hengekøyesete. Høyde: 13 cm. Leveres med to trekk. ",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65985.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/244992",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "Seil Molift RgoSling Toilet HighBack polstret benst delte høy toa poly/PE skum medium personløfter frittstå Molift Smart 150/Molift Mover 180/Molift Mover 205/takmont Molift Air 200",
      hmsnr: "198192",
      serieNr: null,
      datoUtsendelse: "2022-07-25 13:06:05",
      ordrenummer: "8072506",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Molift RgoSling Toilet HighBack Padded medium",
      grunndataBeskrivelse:
        "<p>Polstret toalettseil med høy rygg. Seilet har flere løkker på begge skuldre, og leggbånd for å tilpasse sittevinkelen iht. brukerens behov, inkludert oppreist sittestilling. Beltespennene kan justeres i lengden for fordeling av vekt og trykk, god stabilitet og sikkerhet. Passer til personløfter Molift Smart150/Molift Mover180/Molift Air.</p>",
      grunndataKategori: "Seil til personløftere",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/43143.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/198192",
      grunndataKategoriKortnavn: "Seil",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "183015",
      isoKategori: "Portable/bærbare ramper",
      beskrivelse:
        "Terskeleliminator Eliramp b90 l32-40 h4-5 vekt11,5 last750 gummi løs",
      hmsnr: "170090",
      serieNr: null,
      datoUtsendelse: "2022-06-27 10:24:46",
      ordrenummer: "8056052",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Eliramp b90 h4-5",
      grunndataBeskrivelse:
        "Terskeleliminator med påkjøring fra en side og avrundede sidekanter. Produsert  i gummi med sklisikker overflate. Leveres i bredde 90 cm. og 7 ulike høyder fra 1,5 - 12,5 cm. Kan tilpasses noe til ønsket bredde og dybde.",
      grunndataKategori: "Terskeleliminatorer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/30381.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/170090",
      grunndataKategoriKortnavn: "Terskeleliminator",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181218",
      isoKategori: "Madrasser",
      beskrivelse:
        "Madrass Puls NAV b90 l200 h13 skum brukervekt120 trekk bomull/polyester",
      hmsnr: "174791",
      serieNr: null,
      datoUtsendelse: "2022-05-02 14:28:33",
      ordrenummer: "7981237",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Puls NAV 90 x 200",
      grunndataBeskrivelse:
        "Skummadrass med trekk i bomull og polyester. Både madrass og trekk kan vaskes på 60 grader. Inkontinenstrekk leveres som tilbehør. Leveres i flere størrelser. Høyde: 13 cm. Maks brukervekt: 120 kg.",
      grunndataKategori: "Madrasser skumbaserte",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/64443.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/174791",
      grunndataKategoriKortnavn: "Madrass",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181210",
      isoKategori: "Senger og løse sengebunner med elektrisk regulering",
      beskrivelse:
        "Seng Opus 90DW b90 l200 4delt h36-83 el rygg el ben el 4motor gavl MDF",
      hmsnr: "255799",
      serieNr: "821173",
      datoUtsendelse: "2022-05-02 14:28:33",
      ordrenummer: "7981237",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Opus 90DW",
      grunndataBeskrivelse:
        "Seng med elektrisk regulering av høyde, rygg-, lår- og bendel. Hver del  kan reguleres separat. Sengen kan forlenges med 20 cm uten tilbehør. Leveres til madrassbreddene 90, 110 og 120 cm. Leveres komplett med hode- og fotgavl, samt nedfellbare og avtagbare sengegrinder på begge langsider. Kan vaskes i vaskemaskin. Maks brukervekt: 200 kg.",
      grunndataKategori: "Senger med elektrisk regulering av liggeflaten",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/64440.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/255799",
      grunndataKategoriKortnavn: "Seng",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090706",
      isoKategori: "Posisjoneringsputer og -systemer",
      beskrivelse: "Buepute u/trekk posisjonering CareWave xstor",
      hmsnr: "158944",
      serieNr: null,
      datoUtsendelse: "2022-03-02 14:20:18",
      ordrenummer: "7909112",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Buepute u/trekk posisjonering CareWave xstor",
      grunndataBeskrivelse:
        "Posisjoneringspute i buet form som egner seg til bruk i fanget i sittende eller halvsittende posisjon. Den vil gi stor og god understøttelsesflate for begge armer. Puten egner seg også som ammepute. Putefyll: polystyrenkuler, trekk: toveis elastisk dartex. Det tilbys ulike avtagbare trekk.",
      grunndataKategori: "Posisjoneringsputer og -systemer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/44099.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/158944",
      grunndataKategoriKortnavn: "Posisjoneringsputer",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090706",
      isoKategori: "Posisjoneringsputer og -systemer",
      beskrivelse: "Armpute Hemi u/trekk posisjonering CareWave stor",
      hmsnr: "155132",
      serieNr: null,
      datoUtsendelse: "2022-03-02 14:20:18",
      ordrenummer: "7909112",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "CareWave Hemi-armpute L u/trekk",
      grunndataBeskrivelse:
        "Hemi-armpute er en pute for å stabilisere paretisk arm. Hemiplegikere vil kunne få en stabil/god posisjon uten å være avhengig av bord/armlene. Nedre pute legges i fang, øvre del kan vinkles etter behov. Putene er festet med borrelås. Putefyll: polystyrenkuler, trekk: toveis elastisk dartex. Kommer i flere str, og det tilbys ulike avtagbare trekk.",
      grunndataKategori: "Posisjoneringsputer og -systemer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/44053.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/155132",
      grunndataKategoriKortnavn: "Posisjoneringsputer",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090706",
      isoKategori: "Posisjoneringsputer og -systemer",
      beskrivelse: "S-pute u/trekk posisjonering CareWave stor",
      hmsnr: "147073",
      serieNr: null,
      datoUtsendelse: "2022-03-02 14:20:18",
      ordrenummer: "7909112",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "S-pute u/trekk posisjonering CareWave stor",
      grunndataBeskrivelse: "S-pute u/trekk posisjonering CareWave",
      grunndataKategori:
        "Tilbehør til hjelpemidler for stabilisering av kroppen (ikke-kroppsbårne)",
      grunndataBilde: null,
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/147073",
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "Seil Molift RgoSling HighBack nett benst delte høy bad/hyg poly medium personløfter frittstå Molift Smart 150/Molift Mover 180/Molift Mover 205/takmont Molift Air 200",
      hmsnr: "198178",
      serieNr: null,
      datoUtsendelse: "2022-02-21 11:40:07",
      ordrenummer: "7891155",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Molift RgoSling HighBack Net medium",
      grunndataBeskrivelse:
        "<p>Seil med høy rygg i nett-polyester materiale som puster og tørker svært raskt. Egnet for dusj- og badesituasjoner. Passer til personløfter Molift Smart150/Molift Mover180/Molift Air. </p>",
      grunndataKategori: "Seil til personløftere",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/43129.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/198178",
      grunndataKategoriKortnavn: "Seil",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "Seil Molift RgoSling HighBack polstret benst delte høy poly/PE skum medium personløfter frittstå Molift Smart 150/Molift Mover 180/Molift Mover 205/takmont Molift Air 200",
      hmsnr: "198164",
      serieNr: null,
      datoUtsendelse: "2022-02-21 11:40:07",
      ordrenummer: "7891155",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Molift RgoSling HighBack Padded medium",
      grunndataBeskrivelse:
        "<p>Polstret seil med høy rygg som gir støtte for kroppen og hodet. Glidende løkker forenkler posisjonering i seilet. Passer til personløfter Molift Smart150/Molift Mover180/Molift Air.</p>",
      grunndataKategori: "Seil til personløftere",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/43121.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/198164",
      grunndataKategoriKortnavn: "Seil",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "180915",
      isoKategori: "Lenestoler",
      beskrivelse:
        "Stol oppreis Nova 30 sb47-55 rh72 sd42-53 sh40-48 ind rygg el benst el tilt armlene nedfell smal lav stoff skifergrå",
      hmsnr: "241463",
      serieNr: "771922",
      datoUtsendelse: "2022-01-31 11:56:35",
      ordrenummer: "7845390",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Nova 30",
      grunndataBeskrivelse:
        "Stol med individuell elektrisk regulering av rygg, leggstøtter og oppreisningsfunksjon. Rett og vinklet seteløft, tiltfunksjon. Nedfellbare armlener. Fås med trekk i stoff og hud. Inkontinenstrekk fås som tilbehør. Tåler brukervekt opptil 150 kg.",
      grunndataKategori:
        "Løftestoler med individuell regulering av rygg, benstøtter og oppreisning",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/54609.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/241463",
      grunndataKategoriKortnavn: "Løftestol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222724",
      isoKategori: "Overvåkings- og posisjoneringssystemer",
      beskrivelse:
        "OEBS - ERSTATTET AV 298687 Overvåkingssystem kamera Luvion Prestige Touch 2",
      hmsnr: "289707",
      serieNr: null,
      datoUtsendelse: "2021-09-01 10:31:37",
      ordrenummer: "7650225",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Luvion Prestige Touch 2 kamera",
      grunndataBeskrivelse:
        "Trådløst overvåkingssystem med kamera og 7 tommer digital fargeskjerm. Fjernstyrt og tiltbart kamera. Nattfunksjon med IR-lys. VOX-funksjon (stemmeaktivert monitor). Toveiskommunikasjon. Temperaturmåler. Rekkevidde: 300 m i frisikt. Inntil 4 kameraer kan vises samtidig på skjermen. Kamera og monitor er separate produkter, som må bestilles sammen.",
      grunndataKategori: "Overvåkingssystemer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65142.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/289707",
      grunndataKategoriKortnavn: "Overvåkingssystem",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222724",
      isoKategori: "Overvåkings- og posisjoneringssystemer",
      beskrivelse:
        "OEBS - ERSTATTET AV 298688 Overvåkingssystem monitor Luvion Prestige Touch 2",
      hmsnr: "289708",
      serieNr: null,
      datoUtsendelse: "2021-09-01 10:31:37",
      ordrenummer: "7650225",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Luvion Prestige Touch 2 monitor",
      grunndataBeskrivelse:
        "Trådløst overvåkingssystem med kamera og 7 tommer digital fargeskjerm. Fjernstyrt og tiltbart kamera. Nattfunksjon med IR-lys. VOX-funksjon (stemmeaktivert monitor). Toveiskommunikasjon. Temperaturmåler. Rekkevidde: 300 m i frisikt. Inntil 4 kameraer kan vises samtidig på skjermen. Kamera og monitor er separate produkter, som må bestilles sammen.",
      grunndataKategori: "Overvåkingssystemer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65142.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/289708",
      grunndataKategoriKortnavn: "Overvåkingssystem",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "121224",
      isoKategori: "Rullestolfester i bil",
      beskrivelse: "Rullestolfeste bil Dahl Dockingsystem",
      hmsnr: "159741",
      serieNr: null,
      datoUtsendelse: "2021-08-10 07:25:54",
      ordrenummer: "7621321",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "129012",
      isoKategori: "Personbilregistrerte kassevogner",
      beskrivelse:
        "Bil kv Volkswagen Transporter NAV Høy Lang 2,0 CR 150hk DSG aut",
      hmsnr: "235620",
      serieNr: "691817",
      datoUtsendelse: "2018-07-04 11:49:12",
      ordrenummer: "5908720",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "121212",
      isoKategori: "Bilseter og bilputer med spesielle egenskaper",
      beskrivelse: "Sete bil GS seat 256 el rygg tilt b57",
      hmsnr: "235365",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "121224",
      isoKategori: "Rullestolfester i bil",
      beskrivelse: "Rullestolfeste bil Jany skinnetilpasset",
      hmsnr: "198036",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "121215",
      isoKategori:
        "Personheiser montert i eller på bil (for å løfte en person, men ikke rullestolen)",
      beskrivelse: "Heis person bil Turny HD 480 man sving hø",
      hmsnr: "198021",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "121224",
      isoKategori: "Rullestolfester i bil",
      beskrivelse:
        "Rullestolfeste bil mrs Handicare IN8011 stroppefeste 4pkt mrs/andre hjelpemidler",
      hmsnr: "169680",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "121227",
      isoKategori: "Karosseritilpassinger",
      beskrivelse: "Rullestolgulv HC VW T5 lang",
      hmsnr: "134121",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "121221",
      isoKategori: "Hjelpemidler for å løfte rullestol inn i/opp på bil",
      beskrivelse:
        "Rampe rullestol Kvistberga 270/3 bakmont 3delt man plattf265x80x102 løft400",
      hmsnr: "023670",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "121224",
      isoKategori: "Rullestolfester i bil",
      beskrivelse:
        "Rullestolfeste bil Dahl 3pkt beltesett hreg MB Vito/VW T5 C stolpe",
      hmsnr: "198602",
      serieNr: null,
      datoUtsendelse: "2018-05-28 09:30:27",
      ordrenummer: "6086729",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123103",
      isoKategori: "Sklibrett, sklimatter, vendelaken og vendetepper",
      beskrivelse: "Vendehjm forflytningsduk b100 l200 sett a 2stk",
      hmsnr: "229651",
      serieNr: null,
      datoUtsendelse: "2017-07-13 09:52:18",
      ordrenummer: "5667770",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "Seil Molift RgoSling Ampu MediumBack polstret benst delte medium ampu belte poly/PE skum medium personløfter frittstå Molift Smart 150/Molift Mover 180/Molift Mover 205/takmont Molift Air 200",
      hmsnr: "198199",
      serieNr: null,
      datoUtsendelse: "2017-06-30 12:58:06",
      ordrenummer: "5663315",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Molift RgoSling Ampu MediumBack Padded medium",
      grunndataBeskrivelse:
        "<p>Polstret amputasjonsseil med delte benstøtter og medium rygg. Bendelerne har ekstra lengde for påføring under begge bena. Den har også forlengede stropper for å hindre utglidning av brukers sittestilling. Passer til personløfter Molift Smart150/Molift Mover180/Molift Air.</p>",
      grunndataKategori: "Seil til personløftere",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/register/4fd5bb9f-e11f-451c-86e7-57ba3738aa9f/07bf86fb-4ba5-4411-b5de-3b42b9e63a05.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/198199",
      grunndataKategoriKortnavn: "Seil",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123612",
      isoKategori:
        "Stasjonære personløftere festet til vegg/vegger, gulv og/eller tak",
      beskrivelse:
        "Personløfter takmont/frittstå Likorall 242ES el forflytt man oppheng 2pkt",
      hmsnr: "022987",
      serieNr: "338680",
      datoUtsendelse: "2016-10-27 15:05:23",
      ordrenummer: "5340823",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Likorall 242ES",
      grunndataBeskrivelse: "elektrisk hev/senk, 2 punkt oppheng",
      grunndataKategori:
        "Stasjonære personløftere festet i vegger, gulv og/eller tak ",
      grunndataBilde: null,
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/022987",
      grunndataKategoriKortnavn: "Personløfter",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222715",
      isoKategori: "Kalendere og planleggingssystemer",
      beskrivelse: "OEBS Tidshjm MemoPlanner 11 - ERSTATTET AV 231712",
      hmsnr: "209682",
      serieNr: null,
      datoUtsendelse: "2016-03-21 08:52:46",
      ordrenummer: "5059099",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090305",
      isoKategori: "Kjøreposer og -dresser",
      beskrivelse: "Kjørepose Moritz Senior lammeull",
      hmsnr: "145121",
      serieNr: null,
      datoUtsendelse: "2016-01-15 11:39:52",
      ordrenummer: "4970402",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "Seil Molift RgoSling Ampu HighBack polstret benst delte høy ampu belte poly/PE skum medium personløfter frittstå Molift Smart 150/Molift Mover 180/Molift Mover 205/takmont Molift Air 200",
      hmsnr: "198206",
      serieNr: null,
      datoUtsendelse: "2015-03-16 10:10:19",
      ordrenummer: "4591687",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Molift RgoSling Ampu HighBack Padded medium",
      grunndataBeskrivelse:
        "<p>Polstret amputasjonseil med delte benstøtter og høy rygg. Bendelerne har ekstra lengde for påføring under begge bena, og forlengede stropper for å hindre utglidning av brukers sittestilling. Passer til personløfter Molift Smart150/Molift Mover180/Molift Air.</p>",
      grunndataKategori: "Seil til personløftere",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/43157.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/198206",
      grunndataKategoriKortnavn: "Seil",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123103",
      isoKategori: "Sklibrett, sklimatter, vendelaken og vendetepper",
      beskrivelse: "Sklimatte Multiglide Glideduk b150 l1000 rull",
      hmsnr: "190488",
      serieNr: null,
      datoUtsendelse: "2014-06-19 09:25:27",
      ordrenummer: "4251904",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "MultiGlide SG glideduk rull",
      grunndataBeskrivelse:
        "Nylon glideduk med lav-lav friksjon. Immedia MultiGlide SG er en tynn tubeformet glideduk med ultralav friksjon både på innsiden og på utsiden. Med lav friksjon på begge sider, er MultiGlide SG enklere å plassere under brukeren, så vel som at den er enkel å fjerne. MultiGlide SG bør alltid fjernes etter bruk. Finnes i flere str. ",
      grunndataKategori: "Skli- og vendehjelpemidler, myke uten polstring",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/47911.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/190488",
      grunndataKategoriKortnavn: "Skli-/vendehjelpemiddel",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222718",
      isoKategori: "Personlige alarmer for å varsle om nødsituasjoner",
      beskrivelse: "Epi-alarm Falck 6901 EpiTon registrerer lyd",
      hmsnr: "020678",
      serieNr: null,
      datoUtsendelse: "2013-03-05 09:29:07",
      ordrenummer: "3557396",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Falck 6901 Epiton",
      grunndataBeskrivelse:
        "Epi-alarm som registrerer kortvarig eller langvarig lyd med forskjellige styrker i form av smatting, skriking, hvisking m.m. Den vil ikke kunne skille mellom ulike type lydfrekvenser. Fungerer med All in one Basic og All in one komplett.",
      grunndataKategori: "Anfallsalarmer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/52582.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/020678",
      grunndataKategoriKortnavn: "Anfallsalarm",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222704",
      isoKategori: "Indikatorer",
      beskrivelse:
        "OEBS Sender Falck 6705 Universalsender WT - UTGÅTT FRA PRODUSENT - ERSTATTET AV 135551",
      hmsnr: "135557",
      serieNr: null,
      datoUtsendelse: "2013-03-05 09:29:07",
      ordrenummer: "3557396",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222718",
      isoKategori: "Personlige alarmer for å varsle om nødsituasjoner",
      beskrivelse: "Epi-alarm Falck 6901 EpiTon registrerer lyd",
      hmsnr: "020678",
      serieNr: null,
      datoUtsendelse: "2013-02-21 11:47:15",
      ordrenummer: "3538822",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Falck 6901 Epiton",
      grunndataBeskrivelse:
        "Epi-alarm som registrerer kortvarig eller langvarig lyd med forskjellige styrker i form av smatting, skriking, hvisking m.m. Den vil ikke kunne skille mellom ulike type lydfrekvenser. Fungerer med All in one Basic og All in one komplett.",
      grunndataKategori: "Anfallsalarmer",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/52582.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/020678",
      grunndataKategoriKortnavn: "Anfallsalarm",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222718",
      isoKategori: "Personlige alarmer for å varsle om nødsituasjoner",
      beskrivelse:
        "OEBS Anropsalarm Alert Pager Personsøker mottager lyd/vibrasjon - UFP",
      hmsnr: "175468",
      serieNr: null,
      datoUtsendelse: "2013-02-21 11:47:15",
      ordrenummer: "3538822",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222704",
      isoKategori: "Indikatorer",
      beskrivelse: "Mottaker Falck 6705 WT signal fra 6705 sender",
      hmsnr: "135555",
      serieNr: null,
      datoUtsendelse: "2013-02-21 11:47:14",
      ordrenummer: "3538822",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "222704",
      isoKategori: "Indikatorer",
      beskrivelse:
        "OEBS Sender Falck 6705 Universalsender WT - UTGÅTT FRA PRODUSENT - ERSTATTET AV 135551",
      hmsnr: "135557",
      serieNr: null,
      datoUtsendelse: "2013-02-21 11:47:14",
      ordrenummer: "3538822",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123603",
      isoKategori: "Mobile personløftere med seler og/eller seil",
      beskrivelse:
        "Personløfter frittstå Sabina 2 EE Standard el breg el oppheng 2pkt",
      hmsnr: "014760",
      serieNr: "316210",
      datoUtsendelse: "2011-10-24 13:15:54",
      ordrenummer: "2960070",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Sabina II EE",
      grunndataBeskrivelse:
        "elektrisk hev/senk, 2 punkt oppheng, snudiameter 118 cm",
      grunndataKategori: "Mobile personløftere med ståfunksjon",
      grunndataBilde: null,
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/014760",
      grunndataKategoriKortnavn: "Personløfter",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222430",
      isoKategori: "Porttelefoner",
      beskrivelse:
        "Porttelefon sentralenhet PicoPhone IR-styrt fjernstyrt opplærbar IR-mottaker",
      hmsnr: "028553",
      serieNr: null,
      datoUtsendelse: "2010-11-08 13:36:31",
      ordrenummer: "2460227",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "091203",
      isoKategori: "Flyttbare toalettstoler med og uten hjul",
      beskrivelse:
        "Toastol Chameleon sh42-52 armlene avtag benst hel/avtag/hreg sml delbar",
      hmsnr: "097781",
      serieNr: null,
      datoUtsendelse: "2010-09-21 09:12:53",
      ordrenummer: "2476652",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Chameleon",
      grunndataBeskrivelse:
        "Sete med toalettåpning, armlener, ryggstøtte, understell med ben/låsbare hjul, feste til bekken og bøtte og dekkplate til toalettåpningen. Sammenleggbar for reisebruk",
      grunndataKategori: "Flyttbare toalettstoler",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/24495.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/097781",
      grunndataKategoriKortnavn: "Toalettstol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "122203",
      isoKategori: "Manuelle armdrevne rullestoler",
      beskrivelse:
        "Mrs bak Etac Next Comfort sb38 sd41-47 sh41-55 sete vreg rygg vreg",
      hmsnr: "154732",
      serieNr: "447898",
      datoUtsendelse: "2010-07-08 13:05:22",
      ordrenummer: "2376208",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Etac Next Comfort lang",
      grunndataBeskrivelse:
        "Rullestolen leveres med kompakte dekk, tippesikring, tiltfunksjon sete, armlener, høyderegulerbare kjørehåndtak og nakkestøtte som standard. Setehøyde med skifte av deler (uten pute): 40-49 cm.",
      grunndataKategori: "Manuelle rullestoler allround",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/37538.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/154732",
      grunndataKategoriKortnavn: "Manuell rullestol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "223603",
      isoKategori: "Tastaturer",
      beskrivelse:
        "Tastatur Handy Maxi 19 fingerguide lb50x25 tastene19mm tasterep reg trykketid re",
      hmsnr: "036340",
      serieNr: null,
      datoUtsendelse: "2009-01-19 12:39:46",
      ordrenummer: "1602446",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "OEBS Seil Molift Easy Amputasjon hodest benst delte høy amp polyamid medium - UTGÅTT FRA PRODUSENT",
      hmsnr: "148800",
      serieNr: null,
      datoUtsendelse: "2009-01-06 09:53:41",
      ordrenummer: "1652876",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn:
        "Molift Easy Amputasjon hodestøtte benstøtter delte høy polyamid",
      grunndataBeskrivelse: "-",
      grunndataKategori: "Seil til personløftere",
      grunndataBilde: null,
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/148800",
      grunndataKategoriKortnavn: "Seil",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse:
        "Pute sete ROHO QS1011C M5 Corpus/F3 Corpus/F3 Corpus Jr/F5 Corpus/F5 Corpus VS/F5Corpus VS Jr/X850 Corpus M Jr/X850 Corpus/X850 Corpus Jr sb47 sd50",
      hmsnr: "023340",
      serieNr: null,
      datoUtsendelse: "2008-06-02 11:09:19",
      ordrenummer: "1381447",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "ROHO QUADTRO SELECT HIGH PROFILE",
      grunndataBeskrivelse:
        "Trykkefordelende sittepute med fire luftkamre. Luftmengden i hvert kammer kan tilpasses individuelt (egen låsemekanisme i front). Bruker kan synke inntil 9 cm ned i puten. Hydrostatisk trykkfordeling over hele putens overflate. Laget i neoprengummi, som kan lappes og repareres. Laget i neoprengummi, som kan lappes og repareres. Vaskes i såpevann.",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/31382.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/023340",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181218",
      isoKategori: "Madrasser",
      beskrivelse: "Madrass PULS NAV b90 l200 h13 trekk hygiene",
      hmsnr: "142333",
      serieNr: null,
      datoUtsendelse: "2008-02-18 12:53:51",
      ordrenummer: "1247095",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse:
        "Pute sete ROHO QS1010C M5 Corpus/F3 Corpus/F3 Corpus Jr/F5 Corpus/F5 Corpus VS/F5Corpus VS Jr/X850 Corpus M Jr/X850 Corpus/X850 Corpus Jr sb47 sd45",
      hmsnr: "009079",
      serieNr: null,
      datoUtsendelse: "2008-02-11 10:52:41",
      ordrenummer: "1244680",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "ROHO QUADTRO SELECT HIGH PROFILE",
      grunndataBeskrivelse:
        "Trykkefordelende sittepute med fire luftkamre. Luftmengden i hvert kammer kan tilpasses individuelt (egen låsemekanisme i front). Bruker kan synke inntil 9 cm ned i puten. Hydrostatisk trykkfordeling over hele putens overflate. Laget i neoprengummi, som kan lappes og repareres. Laget i neoprengummi, som kan lappes og repareres. Vaskes i såpevann.",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/31382.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/009079",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse:
        "Pute sete Varilite Evolution PSV b50 d45 hforan9 hbak9 luft skum 1kammer trekk poly",
      hmsnr: "078902",
      serieNr: null,
      datoUtsendelse: "2008-02-04 10:58:34",
      ordrenummer: "1241840",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Varilite Evolution PSV 50x45",
      grunndataBeskrivelse:
        "<p>Trykkfordelende sittepute bestående av en skumdel og en luftdel. Luftmengden tilpasses individuelt med pumpe. Stabil front gir fast underlag ved forflytning. Passer til rullestoler med plan- og hengekøyesete. Høyde: 10 cm. Leveres med to trekk.</p>",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/31049.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/078902",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "090621",
      isoKategori: "Fot-, hæl- og tåbeskyttere",
      beskrivelse: "Beskytter hæl Wima-labben stor avlaster kryssbånd",
      hmsnr: "121725",
      serieNr: null,
      datoUtsendelse: "2008-02-04 09:04:15",
      ordrenummer: "1235005",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 4.0,
      antallEnhet: "STK",
      isoKode: "181503",
      isoKategori: "Forhøyningsklosser og forhøyningsben",
      beskrivelse: "Forhøyningskloss Kombiklossen 2001 b8 d8 h3-12 plast beige",
      hmsnr: "055840",
      serieNr: null,
      datoUtsendelse: "2007-09-10 11:43:15",
      ordrenummer: "1053723",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Kombikloss 2001-5, Bøk ",
      grunndataBeskrivelse:
        "Systemet består av tre forskjellige deler. \nTo typer overdel og en type byggekloss som passer til begge \noverdelene. Leveres i brun og bøk farge.\n\nBåde overdelene og byggeklossene forhøyer 3 cm. Ved bruk av en \n overdel og tre byggeklosser får man en forhøyning på 12 cm som \n standard. Med en byggekloss ekstra blir forhøyningen 15 cm. ",
      grunndataKategori: "Forhøyningsklosser og -plater",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/43321.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/055840",
      grunndataKategoriKortnavn: "Forhøyningshjelpemiddel",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123621",
      isoKategori: "Løfteseler/-seil, seter og bårer",
      beskrivelse:
        "OEBS Seil Easy Molift høy avstivet polyamid medium - UTGÅTT FRA PRODUSENT",
      hmsnr: "002631",
      serieNr: null,
      datoUtsendelse: "2007-08-23 11:51:57",
      ordrenummer: "1034908",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123603",
      isoKategori: "Mobile personløftere med seler og/eller seil",
      beskrivelse:
        "Personløfter frittstå Molift Smart el breg man oppheng 4pkt batt utvendig",
      hmsnr: "021788",
      serieNr: "377061",
      datoUtsendelse: "2007-08-13 11:10:30",
      ordrenummer: "1023679",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Molift Smart",
      grunndataBeskrivelse:
        "elektrisk hev/senk, manuell bredderegulerbar , 4 punkt oppheng, utvendig batteri",
      grunndataKategori: "Mobile personløftere med løftefunksjon",
      grunndataBilde: null,
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/021788",
      grunndataKategoriKortnavn: "Personløfter",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123118",
      isoKategori: "Bærestoler, bæreseler og bærekurver",
      beskrivelse: "Bæresete Transeat SR b43 d44 h40",
      hmsnr: "063400",
      serieNr: null,
      datoUtsendelse: "2007-07-18 14:10:31",
      ordrenummer: "965604",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "123103",
      isoKategori: "Sklibrett, sklimatter, vendelaken og vendetepper",
      beskrivelse: "Glidelaken Wendylett Midi b140 l200 stikklaken hvitt",
      hmsnr: "032866",
      serieNr: null,
      datoUtsendelse: "2007-06-18 10:38:05",
      ordrenummer: "967373",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123103",
      isoKategori: "Sklibrett, sklimatter, vendelaken og vendetepper",
      beskrivelse: "Glidelaken Wendylett Mini b100 l200 stikklaken hvitt",
      hmsnr: "032751",
      serieNr: null,
      datoUtsendelse: "2007-06-18 10:38:05",
      ordrenummer: "967373",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181006",
      isoKategori: "Seteputer og sitteunderlag",
      beskrivelse:
        "Pute sete ROHO QS88C M5 Corpus/F3 Corpus/F3 Corpus Jr/F5 Corpus/F5 Corpus VS/F5Corpus VS Jr/X850 Corpus M Jr/X850 Corpus/X850 Corpus Jr sb38 sd38",
      hmsnr: "004256",
      serieNr: null,
      datoUtsendelse: "2007-05-16 14:17:15",
      ordrenummer: "929509",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "ROHO QUADTRO SELECT HIGH PROFILE",
      grunndataBeskrivelse:
        "Trykkefordelende sittepute med fire luftkamre. Luftmengden i hvert kammer kan tilpasses individuelt (egen låsemekanisme i front). Bruker kan synke inntil 9 cm ned i puten. Hydrostatisk trykkfordeling over hele putens overflate. Laget i neoprengummi, som kan lappes og repareres. Laget i neoprengummi, som kan lappes og repareres. Vaskes i såpevann.",
      grunndataKategori: "Sitteputer for komfort",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/31382.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/004256",
      grunndataKategoriKortnavn: "Sittepute",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090303",
      isoKategori: "UTGÅTT - Overført til 090305 Kjøreposer og -dresser",
      beskrivelse: "OEBS =080606 Regncape Neptun med/stor arm hette",
      hmsnr: "079997",
      serieNr: null,
      datoUtsendelse: "2007-01-08 15:03:19",
      ordrenummer: "766040",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090706",
      isoKategori: "Posisjoneringsputer og -systemer",
      beskrivelse: "Posisjonering nakkepute Corpoform 03B 40x25x6 trekk",
      hmsnr: "034631",
      serieNr: null,
      datoUtsendelse: "2007-01-05 11:52:25",
      ordrenummer: "765220",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Lasal Nakkekrave 3B m/trekk",
      grunndataBeskrivelse:
        "Nakkeputene gir støtte både bak hodet og nakken, og på sidene. Stor og liten nakkepute brukes til støtte av hode og nakke, men kan også brukes til å leiring og armstøtte for små barn. U-formet nakkestøtte er en tynn pute som er lett å forme rundt hals og nakke.",
      grunndataKategori: "Utstyr for posisjonering ",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65607.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/034631",
      grunndataKategoriKortnavn: "Posisjoneringsutstyr",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090706",
      isoKategori: "Posisjoneringsputer og -systemer",
      beskrivelse: "Posisjonering pute Corpoform 07 b30 l60 h8 lagring trekk",
      hmsnr: "059625",
      serieNr: null,
      datoUtsendelse: "2007-01-03 10:40:33",
      ordrenummer: "759141",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Lasal Firkantpute 7 m/trekk",
      grunndataBeskrivelse:
        "Allroundpute som kan brukes i mange situasjoner. Egnet til stabilisering av armer eller ben ved at puten former seg etter kroppen og underlaget.\nDe mindre putene fyller ut tomrom mot ryggstøtte eller seng. De større støtter og stabiliserer mellom eller under ben i rygg- eller sideliggende, under føtter. Kan også brukes ved mageleie for små barn.",
      grunndataKategori: "Utstyr for posisjonering ",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65605.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/059625",
      grunndataKategoriKortnavn: "Posisjoneringsutstyr",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "090706",
      isoKategori: "Posisjoneringsputer og -systemer",
      beskrivelse: "Posisjonering nakkepute Corpoform 03 46x2x4 trekk",
      hmsnr: "063544",
      serieNr: null,
      datoUtsendelse: "2007-01-03 10:40:33",
      ordrenummer: "759141",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Lasal Halvmånepute 3 m/trekk",
      grunndataBeskrivelse:
        "Nakkeputene gir støtte både bak hodet og nakken, og på sidene. Stor og liten nakkepute brukes til støtte av hode og nakke, men kan også brukes til å leiring og armstøtte for små barn. U-formet nakkestøtte er en tynn pute som er lett å forme rundt hals og nakke.",
      grunndataKategori: "Utstyr for posisjonering ",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/65607.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/063544",
      grunndataKategoriKortnavn: "Posisjoneringsutstyr",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "091236",
      isoKategori: "Separate dusjer og/eller lufttørkere til toalett",
      beskrivelse: "TOADUSJ SVAN REMOTE SPYL/TØRK AUTOMATISK 1BRYTER",
      hmsnr: "055244",
      serieNr: null,
      datoUtsendelse: "2006-03-30 09:27:24",
      ordrenummer: "435648",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "222109",
      isoKategori: "Samtaleapparater",
      beskrivelse: "OEBS ZYGO MACAW UNIVERSALSTATIV",
      hmsnr: "060519",
      serieNr: null,
      datoUtsendelse: "2005-11-30 13:03:47",
      ordrenummer: "227571",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "241303",
      isoKategori: "Fjernstyringssystemer",
      beskrivelse: "Sender IR Gewa Prog 3 skanning 1-5brytere joystick",
      hmsnr: "029137",
      serieNr: null,
      datoUtsendelse: "2005-11-30 13:03:47",
      ordrenummer: "227571",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "240918",
      isoKategori: "Strømbrytere (av- og på-funksjon)",
      beskrivelse: "OEBS BRYTER,JELLY-BEAN,RØD,FALCK 621901",
      hmsnr: "042100",
      serieNr: null,
      datoUtsendelse: "2005-07-13 14:35:33",
      ordrenummer: "150258",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "240918",
      isoKategori: "Strømbrytere (av- og på-funksjon)",
      beskrivelse: "OEBS BRYTER,JELLY-BEAN,RØD,FALCK 621901",
      hmsnr: "042100",
      serieNr: null,
      datoUtsendelse: "2005-07-13 14:35:33",
      ordrenummer: "150258",
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "183015",
      isoKategori: "Portable/bærbare ramper",
      beskrivelse:
        "Skinne Stepless teleskop l202 b18 alu vekt7 riller friksjon last175",
      hmsnr: "017332",
      serieNr: null,
      datoUtsendelse: "2004-10-12 08:19:35",
      ordrenummer: "9594",
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Stepless",
      grunndataBeskrivelse:
        "lengde 202 cm, bredde 18 cm, aluminium, vekt 6 kg, riller, friksjon, bæreevne 175 kg",
      grunndataKategori: "Teleskopiske kjøreskinner",
      grunndataBilde: null,
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/017332",
      grunndataKategoriKortnavn: "Kjøreskinner",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "122292",
      isoKategori: "Tilbehør til manuelle rullestoler ¿ sete, rygg og hode",
      beskrivelse: "OEBS HØYTRYKKPUMPE BATTERID.M/LADER ART.000071042",
      hmsnr: "032738",
      serieNr: null,
      datoUtsendelse: "2004-02-02 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123103",
      isoKategori: "Sklibrett, sklimatter, vendelaken og vendetepper",
      beskrivelse: "OEBS LØFTESETE TRANSEAT M/BÆRESTROPPER",
      hmsnr: "032908",
      serieNr: null,
      datoUtsendelse: "2002-12-19 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "122203",
      isoKategori: "Manuelle armdrevne rullestoler",
      beskrivelse:
        "Mrs bak akt Kuschall Compact Neo sb45 sd40 sh47-50 sete vreg rygg hreg",
      hmsnr: "014944",
      serieNr: "210973",
      datoUtsendelse: "2002-08-20 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "123106",
      isoKategori: "Dreieskiver",
      beskrivelse: "OEBS DREIETÅRN H.90-120CM 022-680000000",
      hmsnr: "032843",
      serieNr: null,
      datoUtsendelse: "2002-02-28 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "091203",
      isoKategori: "Flyttbare toalettstoler med og uten hjul",
      beskrivelse:
        "Dusjtoastol Chameleon sb45 sh45-55 hjul armlene avtag ryggbånd dekkpl benst avtag sml",
      hmsnr: "015775",
      serieNr: null,
      datoUtsendelse: "1999-07-01 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "091203",
      isoKategori: "Flyttbare toalettstoler med og uten hjul",
      beskrivelse:
        "Dusjtoastol Mobil Tipp Man sb48 sh60 hjul armlene fellbar sete utsp benst avtag tilt man",
      hmsnr: "008112",
      serieNr: null,
      datoUtsendelse: "1998-11-16 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Mobil Tipp med gassfjær",
      grunndataBeskrivelse:
        "setehøyde 60 cm, hjul, oppfellbar armlene, ryggbånd, sete utsparing",
      grunndataKategori: "Kombinerte dusj- og toalettstoler",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/30086.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/008112",
      grunndataKategoriKortnavn: "Dusj-/toalettstol",
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "241303",
      isoKategori: "Fjernstyringssystemer",
      beskrivelse: "OEBS XXXOMGIVELSESKONTROLL FRA GEWA",
      hmsnr: "036106",
      serieNr: null,
      datoUtsendelse: "1998-02-16 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "182403",
      isoKategori: "Tappearmaturer",
      beskrivelse: "OEBS XXXXVVS-UTSTYR SOM SPES,",
      hmsnr: "033938",
      serieNr: null,
      datoUtsendelse: "1997-11-28 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181506",
      isoKategori: "Høyderegulerbare sokler og konsoller",
      beskrivelse: "OEBS KJØKKENINNREDNING SOM SPESIFISERT",
      hmsnr: "034015",
      serieNr: null,
      datoUtsendelse: "1997-09-24 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "181506",
      isoKategori: "Høyderegulerbare sokler og konsoller",
      beskrivelse: "OEBS KJØKKENINNREDNING SOM SPESIFISERT",
      hmsnr: "034015",
      serieNr: null,
      datoUtsendelse: "1997-09-24 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "091225",
      isoKategori:
        "Frittstående og gulv/veggmonterte armlener, støttehåndtak og/eller ryggstøtter til toalettet",
      beskrivelse: "Toaarmstøtte Optima Låsbar armlene oppfell fast",
      hmsnr: "001628",
      serieNr: null,
      datoUtsendelse: "1997-09-01 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: true,
      grunndataProduktNavn: "Optima låsbar",
      grunndataBeskrivelse: "veggmontert",
      grunndataKategori: "Armlener til toalett - ikke toalettmonterte",
      grunndataBilde:
        "https://finnhjelpemiddel.nav.no/imageproxy/400d/orig/24491.jpg",
      hjelpemiddeldatabasenURL:
        "https://finnhjelpemiddel.intern.dev.nav.no/produkt/hmsartnr/001628",
      grunndataKategoriKortnavn: "Toalettarmstøtte",
    },
    {
      antall: 2.0,
      antallEnhet: "STK",
      isoKode: "183015",
      isoKategori: "Portable/bærbare ramper",
      beskrivelse: "OEBS KJØRERAMPE TELESKOP, 170-300",
      hmsnr: "033920",
      serieNr: null,
      datoUtsendelse: "1996-04-16 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
    {
      antall: 1.0,
      antallEnhet: "STK",
      isoKode: "183018",
      isoKategori: "Stasjonære/fastmonterte ramper",
      beskrivelse: "OEBS XXXXTOPRO KJØREBRO KOMPLETT.",
      hmsnr: "033999",
      serieNr: null,
      datoUtsendelse: "1993-09-02 00:00:00",
      ordrenummer: null,
      status: "I utlån",
      grunndataBeriket: false,
      grunndataProduktNavn: null,
      grunndataBeskrivelse: null,
      grunndataKategori: null,
      grunndataBilde: null,
      hjelpemiddeldatabasenURL: null,
      grunndataKategoriKortnavn: null,
    },
  ],
});
